### PR TITLE
Add classes

### LINKED ISSUE #26: Create database java classes
Create a java class matching every database table.
- Customer
- Service
- Appointment (needs fix)
- Calendar
- Unavailable
- There may be some others

Also create the AppointmentSlot class.

Check out the [application design](https://github.com/jerometujague/SoftwareEngineeringProject/wiki/Application-Design) for a better overview of the classes and their functions.

### PR DESCRIPTION
**Pull request by dbruce**
Added model classes, mappers, DAO, and service Controller. Closes #26.

### CODE REVIEW

**Comment by jmbockhorst** [comment]
@dbruce Why did you close this?

**Comment by dbruce** [comment]
Mistake, sorry.

**Comment by jmbockhorst** [comment]
After looking at the database updates, here are the changes we will need to make.

**Calendar**

For now, we will only need these variables:
* int calendarId
* LocalDate date
* boolean isHolliday

**AppointmentSlot**

* date and type variables should both be of String type.

**Unavailable**

* dateId should be named date of type LocalDate
* timeId should be named time of type LocalTime
* branchId, serviceId, and managerId should be of type Integer
  * In the mapper, you will have to do (Integer)rs.getObject("branch_id")
* A new field call dayOfWeek of Integer type should be added

**Appointment**

* timeId should be time of time LocalTime


To get the LocalDate and LocalTime objects in the mapper, you can do this:
* rs.getTime("time").toLocalTime();
* rs.getDate("date").toLocalDate();

**Comment by jmbockhorst** [comment]
Oh, and remove serviceId from Unavailable. I know it's in the database but we won't need it. A service won't be unavailable in general, but it'll be unavailable when the managers are unavailable to offer that service.

**Comment by jmbockhorst** [comment]
So I forgot to mention this. In the mapper, when we are getting a date that can be null, specifically in UnavailableMapper (there might be others), we need to check if it is null before trying to call .toLocalDate(). That will create a null pointer exception. So do something like this: 
`rs.getDate("date_") == null ? null : rs.getDate("date_").toLocalDate()`

**Comment by dbruce** [comment]
I will look at the null checking tomorrow. And I also need to learn how to write the POST request logic in the relevant controllers. I just put a placeholder in the UnavailableController for now.

**Comment by jmbockhorst** [comment]
Sounds good. The post function won't return anything, and the function in the controller will make the call to the DAO, which is where the database query will be made.

**Comment by jmbockhorst** [comment]
One more thing I noticed, "timeId" in Appointment should be just "time".

**Pull request merged**
