### PR TITLE
Added calendar table

### PR DESCRIPTION
**Pull request by jerometujague**
Added calendar table. Changed name of appointment_times table.

### CODE REVIEW

**Comment by jerometujague** [comment]
Changes made: 
Accidentally altered service, branch and manager IDs in appointment table instead of unavailable table, which has been fixed. 
Also removed day_name from appointment table and added to unavailable table 
Appointment table changed time_id to time type and name time.
Name field added to branch.

**Comment by jerometujague** [comment]
Added day_of_week field to branch_hours.

**Comment by jmbockhorst** [comment]
Do we need day_name in unavailable table?
Also, can we make day_of_week in branch table an int?

**Comment by jerometujague** [comment]
In the unavailable table, day_name will let us say 4:00 for every Wednesday from now on is unavailable. 
Changed day_of_week in branch_hours table to int.

**Comment by jmbockhorst** [comment]
So in the unavailable table, to make something blocked for every Monday, for example, were could let date_id be null, and then we would need another day_of_week field. I don't know if there is a better way of doing that.

**Comment by jmbockhorst** [comment]
Okay, then lets use an int for that.

**Comment by jmbockhorst** [comment]
And then it needs be able to be null, if it applies for just one certain day. Also, should date_id be able to be null, if we are using day_of_week.

**Comment by jerometujague** [comment]
Date_id can't be null because it's a foreign ke
We could add a new field and just call it date, so if date is null that means it's just for the upcoming named weekdays like Wednesday or whatever.

**Comment by jmbockhorst** [comment]
Or when we are using day_of_week for an every week unavailability, we could just put like 1 or something in date_id and ignore it when day_of_week is not null.

**Comment by jerometujague** [comment]
Changed date_id to date_
It is no longer a foreign key so it can be null. This way is probably easier, if the date_ is set then its unavailable for that date, but if date_ is null then we can set day_name and let it be unavailable for every week.

**Comment by jmbockhorst** [comment]
Looks good. Is there a reason you are using the string day name? I think it would be easier to process an int, since everything will be ints except for when we send it to the front end.

**Comment by jerometujague** [comment]
No, I just wasn't sure what we wanted to use, but I will go ahead and change day name to int.

**Pull request merged**
