### PR TITLE
Performed database normalization and datafill

### PR DESCRIPTION
**Pull request by jerometujague**
On the branch_hours table, I created a procedure to fill out default time slots for Monday-Friday from 8:00Am to 5:00PM for every branch. We can adjust this as needed.
I created a procedure to auto fill out unavailable slots for future days.
I can create procedures to auto insert into unavailable_branch and unavailable_manager in the next update if we need to.
Also created more data to test with.

### CODE REVIEW

**Comment by jerometujague** [comment]
Forgot to include my day adjustment. Will do that in next commit. 
I was going to ask you about that, what are we using branch hours for? I just generated time slots for each potential appointment on each day, but we can do it the way you said if that is easier for our purposes.

**Comment by jmbockhorst** [comment]
I was planning on using it to loop from open hour to close hour and adding all of those as appointment slots. It was easier in java to implement it that way.

**Comment by jerometujague** [comment]
Oh okay, I will change it to do that then.

**Comment by jmbockhorst** [comment]
Something we didn't think about... So right now, there is nothing in branch_unavailable or manager_unavailable, which means nothing in the unavailable table matters. Will we have to have matching rows in those tables if we wanted to make it unavailable weekly for a specific branch? That's something we would probably need to add to the routine. Maybe optional inputs for branch_id or manager_id. That way the routine will know which one to do.

**Comment by jerometujague1** [comment]
Oh I had already started working on that, I was going to do a separate branch but I will just include it in a commit for this one since I’m almost done. 
I’ve got it to check for duplicate entries, as well as add entries to branch unavailable or manager unavailable if we put in the correct input.

**Comment by jerometujague** [comment]
So for the procedure, if manager_unavailable is being updated, input value for branch_unavailable will be 0 and vice versa.

**Pull request merged**
